export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SET_MEMBERS_DATA = "SET_MEMBERS_DATA";
export const FILTER_MEMBERS_DATA = "FILTER_MEMBERS_DATA";
export const ADD_MEMBERS_DATA = "ADD_MEMBERS_DATA";
export const DELETE_MEMBERS_DATA = "DELETE_MEMBERS_DATA";